apiVersion: v1
kind: Service
metadata:
  name: tetragon-demo-app-service
  labels:
    app: tetragon-demo-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  selector:
    app: tetragon-demo-app